#! /bin/sh
PATH=/sbin:/bin:/usr/sbin:/usr/bin
LD_LIBRARY_PATH=/lib:/usr/lib:/usr/local/lib
export PATH LD_LIBRARY_PATH

/bin/mount -a
/sbin/mdev -s
/bin/mount -a

mount -t 9p -o trans=virtio,version=9p2000.L,msize=16384 hostshare /mnt/

echo QEMU-SANYUJOJO > /proc/sys/kernel/hostname

dmesg -n 1
chmod 666 /dev/null

echo "---------------------------------------------"
echo " Welcome debugging on  SanyuJoJo board! "
echo "---------------------------------------------"
